apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hello-spring-dev

resources:
  - ../../base

patchesStrategicMerge:
  - backend-debug-env.yml

configMapGenerator:
  - name: env-config
    literals:
      - INFRA_NAMESPACE=hello-spring-dev
