version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: hello_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    build: hello-spring/
    image: hello-backend
    container_name: hello-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  react:
    build: hello-frontend/
    image: hello-frontend
    container_name: hello-frontend
    ports:
      - "3000:80"
    depends_on:
      - app
