apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#commonLabels:
#  app: blue-green

namespace: hello-spring

resources:
  - ns.yml
  - postgres.yml
  - backend.yml
  - frontend.yml
  - ingress.yml
