apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hello-spring

resources:
  - ../../base

configMapGenerator:
  - name: env-config
    literals:
      - INFRA_NAMESPACE=infra
